owner: marketplace-team
dbup:
  enabled: false
api:
  enabled: true
  hosts:
    - mpt-platform-api.domain.global
worker:
  enabled: false
env:
  ExtMptProductExtensionMapping:
    name: EXT_MPT_PRODUCT_EXTENSION_MAPPING
  mptPublicApiUrl:
    name: MPT_API_BASE_URL
  MptToolStorageAirtableBaseId:
    name: MPT_TOOL_STORAGE_AIRTABLE_BASE_ID
  MptToolStorageAirtableTableName:
    name: MPT_TOOL_STORAGE_AIRTABLE_TABLE_NAME
    defaultValue: "Migrations"
  MptToolStorageType:
    name: MPT_TOOL_STORAGE_TYPE
    defaultValue: "airtable"
  AppInsightsConnectionString:
    name: SDK_APPLICATIONINSIGHTS_CONNECTION_STRING
  SdkExtensionId:
    name: SDK_EXTENSION_ID
  SdkExtensionUrl:
    name: SDK_EXTENSION_URL
  SdkOtelServiceName:
    name: SDK_OTEL_SERVICE_NAME
    defaultValue: "Swo.Installation.Extension"
  SdkZitiWorkers:
    name: SDK_ZITI_WORKERS
    defaultValue: "4"
secrets:
  MptToolStorageAirtableApiKey:
    name: MPT_TOOL_STORAGE_AIRTABLE_API_KEY
  SdkExtensionApiKey:
    name: SDK_EXTENSION_API_KEY
cronjobs: {}